version: "3.7"
services:
  api:
    build: ./server
    environment: 
      - PORT=5000
    ports:
      - "8081:5000"
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: testdb
    volumes:
      - ./data:/data/db